[".local/share/fcitx5/rime"]
    type = "git-repo"
    url = "https://github.com/iDvel/rime-ice.git"
    refreshPeriod = "168h"
    clone.depth = 1

[".tmux/plugins/tpm"]
    type = "git-repo"
    url = "https://github.com/tmux-plugins/tpm.git"
    refreshPeriod = "168h"
    clone.depth = 1
